//! The code-sandbox bridge's untrusted-input handling (noevia#999), ported from noevia-core's
//! `code-sandbox/pi-acp-bridge.cjs` and `code-sandbox/supervisor.cjs`:
//!
//! - [`frame`]: `lines()`, the strict LF JSONL framing of the agent's and the client's streams;
//! - [`tool_call`]: `toolCallFor()`, the ACP tool call built from the agent's report;
//! - [`start`]: the supervisor's start-message parsing (`noevia: 'start'`, `cwd`, allowlisted env);
//! - [`contain`]: the pure part of `insideRoot()` (the realpath step stays in JS).
//!
//! Each agrees with the JS reference on the shared fixtures (`tests/fixtures/sandbox-bridge.v1.json`,
//! generated by noevia-core `tools/gen-sandbox-bridge-fixtures.cjs`). noevia-core loads this crate
//! as `sandbox-bridge.wasm` (bins/sandbox-bridge-wasm) behind `SANDBOX_BRIDGE_IMPL=rust`.

pub mod contain;
pub mod frame;
pub mod js;
pub mod json;
pub mod start;
pub mod tool_call;
