//! Differential test against the Python reference (noevia#981): every case in
//! tests/fixtures/docx-text.v1.json (synthetic DOCX documents generated by
//! tools/gen-docx-text.py, with noevia-services' ocr/docx_text.py producing the `python`
//! results) must give exactly the recorded `rust` result, and the recorded pair must keep the
//! safety rule: this crate never extracts what Python refuses, never extracts different text,
//! and hand-written cases refuse with Python's class unless a `stricter` reason is recorded.
//! The same file is committed in noevia-services, where CI `cmp`s the two copies and replays
//! it against the live Python function and the built binary.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use serde_json::{json, Value};
use sha2::{Digest, Sha256};

fn b64(s: &str) -> Vec<u8> {
    let val = |c: u8| -> u32 {
        match c {
            b'A'..=b'Z' => u32::from(c - b'A'),
            b'a'..=b'z' => u32::from(c - b'a') + 26,
            b'0'..=b'9' => u32::from(c - b'0') + 52,
            b'+' => 62,
            b'/' => 63,
            _ => panic!("bad base64"),
        }
    };
    let bytes: Vec<u8> = s.bytes().filter(|&c| c != b'=').collect();
    let mut out = Vec::new();
    for chunk in bytes.chunks(4) {
        let n = chunk.iter().fold(0u32, |a, &c| (a << 6) | val(c)) << (6 * (4 - chunk.len()));
        let b = n.to_be_bytes();
        out.extend_from_slice(&b[1..chunk.len()]);
    }
    out
}

fn record(r: &Result<docx_text::Extracted, docx_text::Refusal>) -> Value {
    match r {
        Err(e) => json!({"error": e.class()}),
        Ok(e) if e.text.chars().count() > 2000 => json!({
            "text_sha256": format!("{:x}", Sha256::digest(e.text.as_bytes())),
            "text_chars": e.text.chars().count(),
            "truncated": e.truncated,
        }),
        Ok(e) => json!({"text": e.text, "truncated": e.truncated}),
    }
}

#[test]
fn every_fixture_matches_and_is_never_more_lenient_than_python() {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/docx-text.v1.json"
    ))
    .unwrap();
    let doc: Value = serde_json::from_str(&text).unwrap();
    let cases = doc["cases"].as_array().unwrap();
    let (mut hand, mut mutants, mut agreed_ok, mut stricter) = (0, 0, 0, 0);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let data = b64(c["docx"].as_str().unwrap());
        let got = record(&docx_text::extract_docx(&data));
        assert_eq!(got, c["rust"], "{name}: binary result changed");
        let py = &c["python"];
        if got.get("error").is_none() {
            assert_eq!(&got, py, "{name}: more lenient than Python");
            agreed_ok += 1;
        } else if py.get("error").is_none() {
            stricter += 1;
        }
        if c["kind"] == "case" {
            hand += 1;
            if c.get("stricter").is_none() {
                assert_eq!(&got, py, "{name}: refusal class differs from Python");
            } else {
                assert!(got.get("error").is_some(), "{name}: declared stricter");
            }
        } else {
            mutants += 1;
        }
    }
    assert!(hand >= 100, "hand-written cases shrank: {hand}");
    assert!(mutants >= 500, "mutants shrank: {mutants}");
    println!("{hand} cases, {mutants} mutants, {agreed_ok} identical extractions, {stricter} stricter refusals");
}

/// Producer compatibility (tools/gen-docx-producers.py): DOCX files written by python-docx,
/// pandoc, LibreOffice, macOS textutil and zip re-packers (synthetic content) must all be
/// extracted, with Python's exact text, except the recorded deliberate refusals.
#[test]
fn every_producer_file_is_extracted_like_python() {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/docx-producers.v1.json"
    ))
    .unwrap();
    let doc: Value = serde_json::from_str(&text).unwrap();
    let cases = doc["cases"].as_array().unwrap();
    assert!(cases.len() >= 14, "producer set shrank: {}", cases.len());
    let mut extracted = 0;
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let got = record(&docx_text::extract_docx(&b64(c["docx"].as_str().unwrap())));
        assert_eq!(got, c["rust"], "{name}: result changed");
        assert!(
            c["python"].get("error").is_none(),
            "{name}: Python refused a producer file"
        );
        if c.get("stricter").is_some() {
            assert!(got.get("error").is_some(), "{name}: declared refusal");
        } else {
            assert_eq!(
                &got, &c["python"],
                "{name}: producer file not extracted like Python"
            );
            extracted += 1;
        }
    }
    println!("{extracted} producer files extracted identically");
}
