#!/usr/bin/env python3
"""Generate crates/model-files' Unicode tables and differential fixtures (noevia#964).

The reference is noevia-services' model-manager/app/model_files.py (`files_from_tree_py`, the
Hugging Face tree listing -> file entries function). Its regexes run on Python's Unicode
database (\\w, \\d, IGNORECASE folds, str.lower/upper, int() of non-ASCII digits and spaces), so
the tables the Rust port needs are derived here, from the same interpreter the service runs on:

    uv run --python 3.12 tools/gen-model-files.py --model-manager <noevia-services>/model-manager

Writes crates/model-files/src/pytables.rs and crates/model-files/tests/fixtures/model-files.v1.json.
The fixture file is copied verbatim into noevia-services (model-manager/tests/fixtures/). Every
input is synthetic: invented repository paths and sizes, never a real listing.
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CRATE = ROOT / "crates" / "model-files"
SERVICE_PYTHON = (3, 12)


def ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    for cp in range(0x110000):
        if 0xD800 <= cp < 0xE000 or not pred(chr(cp)):
            continue
        if out and out[-1][1] == cp - 1:
            out[-1] = (out[-1][0], cp)
        else:
            out.append((cp, cp))
    return out


def all_chars():
    return (chr(cp) for cp in range(0x110000) if not 0xD800 <= cp < 0xE000)


def tables() -> str:
    word = ranges(lambda c: re.match(r"\w", c) is not None)
    assert word == ranges(lambda c: c.isalnum() or c == "_")
    digits = ranges(lambda c: re.match(r"\d", c) is not None)
    for lo, hi in digits:
        # Nd comes in runs of ten starting at a zero (a Unicode stability guarantee); the Rust
        # side takes a digit's value as its offset in its run, mod 10.
        assert (hi - lo + 1) % 10 == 0, (hex(lo), hex(hi))
        for cp in range(lo, hi + 1):
            assert unicodedata.decimal(chr(cp)) == (cp - lo) % 10
            assert chr(cp).upper() == chr(cp)
    assert sum(hi - lo + 1 for lo, hi in digits) == sum(
        1 for c in all_chars() if unicodedata.decimal(c, None) is not None)
    space = [ord(c) for c in all_chars() if c.isspace()]
    folds = {}
    for lit in "IQFBP_0123456789":
        folds[lit] = [ord(c) for c in all_chars() if re.fullmatch(re.escape(lit), c, re.I)]
    cls = [ord(c) for c in all_chars() if re.fullmatch("[A-Z0-9]", c, re.I)]
    upper_src = sorted({cp for v in folds.values() for cp in v} | set(cls))
    upper = [(cp, chr(cp).upper()) for cp in upper_src if not chr(cp).isascii()]
    # str.lower() of a non-ASCII char either has no ASCII in it or ends in a non-ASCII char,
    # except for the chars listed here (whose lower() is entirely ASCII). Suffix tests against
    # an ASCII suffix only need those.
    lower_ascii = []
    for c in all_chars():
        if c.isascii():
            continue
        low = c.lower()
        if all(x.isascii() for x in low):
            if low != c:
                lower_ascii.append((ord(c), low))
        else:
            assert not low[-1:].isascii() or low == c, hex(ord(c))

    def arr(name: str, typ: str, items: list[str], per_line: int = 6) -> str:
        lines = [f"pub const {name}: &[{typ}] = &["]
        for i in range(0, len(items), per_line):
            lines.append("    " + " ".join(x + "," for x in items[i:i + per_line]))
        lines.append("];")
        return "\n".join(lines)

    def pair(lo: int, hi: int) -> str:
        return f"(0x{lo:X}, 0x{hi:X})"

    def rs_str(s: str) -> str:
        return '"' + "".join(f"\\u{{{ord(ch):X}}}" if not ch.isascii() or not ch.isprintable()
                             else ch for ch in s) + '"'

    parts = [
        "// @generated by tools/gen-model-files.py from Python's Unicode database. Do not edit.",
        "//! Character classes as Python's `re` and `str` see them (see tools/gen-model-files.py).",
        "",
        "/// `unicodedata.unidata_version` of the interpreter the tables came from.",
        f'pub const UNIDATA_VERSION: &str = "{unicodedata.unidata_version}";',
        "",
        "/// `re` `\\w` (str.isalnum() or '_'), inclusive code point ranges.",
        arr("WORD", "(u32, u32)", [pair(a, b) for a, b in word]),
        "",
        "/// `re` `\\d` (Unicode Nd), inclusive ranges; a digit's value is (cp - start) % 10.",
        arr("DECIMAL", "(u32, u32)", [pair(a, b) for a, b in digits]),
        "",
        "/// str.isspace().",
        arr("SPACE", "u32", [f"0x{cp:X}" for cp in space], 10),
        "",
    ]
    for lit, cps in folds.items():
        name = "FOLD_UNDERSCORE" if lit == "_" else f"FOLD_{lit}"
        parts += [f"/// Characters `re.IGNORECASE` matches for the literal {lit!r}.",
                  arr(name, "u32", [f"0x{cp:X}" for cp in cps], 10), ""]
    parts += [
        "/// Characters `[A-Z0-9]` matches under `re.IGNORECASE`.",
        arr("CLASS_AZ09", "u32", [f"0x{cp:X}" for cp in cls], 10),
        "",
        "/// str.upper() of the non-ASCII characters the quant pattern can match.",
        arr("UPPER", "(u32, &str)", [f"(0x{cp:X}, {rs_str(u)})" for cp, u in upper], 4),
        "",
        "/// Non-ASCII characters whose str.lower() is entirely ASCII.",
        arr("LOWER_ASCII", "(u32, &str)", [f"(0x{cp:X}, {rs_str(u)})" for cp, u in lower_ascii], 4),
        "",
    ]
    return "\n".join(parts)


# --- fixtures ---------------------------------------------------------------------------------

def f(path, **extra) -> dict:
    return {"type": "file", "path": path, **extra}


def cases() -> list[tuple[str, str]]:
    """(name, JSON text of the entries) pairs. JSON text, not values, so that NaN, huge integer
    literals, duplicate keys and escapes reach both parsers exactly as written."""
    out: list[tuple[str, str]] = []

    def add(name: str, entries) -> None:
        out.append((name, entries if isinstance(entries, str) else json.dumps(entries)))

    # Listings shaped like the hub's.
    add("empty", [])
    add("plain_gguf", [f("model-Q4_K_M.gguf", size=123)])
    add("lfs_size_wins", [f("m.Q8_0.gguf", size=1, lfs={"size": 999, "oid": "x"})])
    add("lfs_zero_falls_back", [f("m.gguf", size=7, lfs={"size": 0})])
    add("lfs_without_size", [f("m.gguf", size=7, lfs={"oid": "x"})])
    add("no_size_is_zero", [f("m.gguf")])
    add("directory_skipped", [{"type": "directory", "path": "sub"}, f("sub/x-IQ2_XXS.gguf", size=3)])
    add("non_gguf_skipped", [f("README.md", size=5), f("config.json", size=2), f("x.safetensors")])
    add("support_files", [f("mmproj-F16.gguf"), f("vision.mmproj"), f("chat_template.jinja"),
                          f("sub/tokenizer.model"), f("tokenizer.model.bak")])
    add("case_insensitive_ext", [f("BIG.GGUF", size=1), f("MMPROJ.GGUF"), f("x.Gguf")])
    add("shard_set", [f(f"Q4_K_M/model-Q4_K_M-{i:05d}-of-00003.gguf", size=10 + i) for i in (1, 2, 3)])
    add("shard_set_mixed_dirs", [f("a/m-00001-of-00002.gguf"), f("b/m-00002-of-00002.gguf")])
    add("missing_type_and_path", [{"path": "x.gguf"}, {"type": "file"}, {}])
    add("type_not_string", [{"type": 1, "path": 5}, {"type": None, "path": None}, {"type": ["file"]}])
    add("non_file_with_bad_path_skipped", [{"type": "directory", "path": 5}])
    add("duplicate_keys_last_wins", '[{"type":"file","path":"a.gguf","path":"b-Q5_K_S.gguf","size":1,"size":2}]')
    add("key_order_irrelevant", '[{"size":9,"path":"z.gguf","type":"file"}]')
    add("escaped_unicode", '[{"type":"file","path":"\\u00e9-\\ud83d\\ude00-Q6_K.gguf","size":1}]')
    add("whitespace_everywhere", ' [ { "type" : "file" ,\n\t"path" : "w.gguf" , "size" : 4 } ]\r\n')

    # Quant labels.
    for name, path in [
        ("quant_lower", "m.q4_k_m.gguf"), ("quant_iq", "m-IQ3_XXS.gguf"), ("quant_bf16", "m-BF16.gguf"),
        ("quant_fp8", "m-fp8.gguf"), ("quant_fp4", "m.FP4.gguf"), ("quant_f32", "m.f32.gguf"),
        ("quant_none", "model.gguf"), ("quant_glued_left", "xQ4_K.gguf"), ("quant_glued_right", "Q4_Kx.gguf"),
        ("quant_trailing_underscore", "m-Q4_.gguf"), ("quant_long_tail", "m-Q4_K_M_L_XL_0.gguf"),
        ("quant_first_wins", "m-Q2_K-Q8_0.gguf"), ("quant_in_dir", "Q5_K_M/model.gguf"),
        ("quant_digits_only", "m-Q12345.gguf"), ("quant_F16_vs_Q", "F16-Q4_0.gguf"),
        ("quant_ud_prefix", "m-UD-Q4_K_XL.gguf"), ("quant_backtrack_tail", "m-Q4_K_é.gguf"),
        ("quant_word_after_digit", "m-Q4é.gguf"), ("quant_superscript", "m-Q4².gguf"),
        ("quant_arabic_digits", "m-Q٤_K.gguf"), ("quant_fullwidth_digit", "m-Q４.gguf"),
        ("quant_dotted_I", "m-İQ4_K.gguf"), ("quant_dotless_i", "m-ıq4_k.gguf"),
        ("quant_long_s", "m-Q4_ſ.gguf"), ("quant_kelvin", "m-Q4_K_M.gguf"),
        ("quant_combining_mark", "m-Q4_Ḱ.gguf"), ("quant_underscore_word", "_Q4_K.gguf"),
        ("quant_bf16_glued", "BF16x.gguf"), ("quant_iq_no_digit", "m-IQ_K.gguf"),
        ("quant_mmproj_f16", "mmproj-model-f16.gguf"), ("quant_newline", "m-Q4_K\n.gguf"),
    ]:
        add(name, [f(path, size=1)])

    # Shard names.
    for name, path in [
        ("shard_basic", "m-00001-of-00002.gguf"), ("shard_upper_of", "m-00001-OF-00002.gguf"),
        ("shard_six_digits", "m-000001-of-000002.gguf"), ("shard_four_digits", "m-0001-of-0002.gguf"),
        ("shard_inner_dot", "m-00001-of-00002.part.gguf"), ("shard_two_patterns", "a-00001-of-00009-00002-of-00003.gguf"),
        ("shard_arabic", "m-٠٠٠٠١-of-٠٠٠٠٢.gguf"),
        ("shard_fullwidth", "m-００００１-of-００００３.gguf"),
        ("shard_math_digits", "m-\U0001d7ce\U0001d7ce\U0001d7ce\U0001d7d8\U0001d7e1-of-\U0001d7ce\U0001d7ce\U0001d7ce\U0001d7cf\U0001d7d0.gguf"),
        ("shard_zero_of_zero", "m-00000-of-00000.gguf"), ("shard_index_past_total", "m-00009-of-00002.gguf"),
        ("shard_only_suffix", "-00001-of-00002.gguf"), ("shard_in_directory", "m-00001-of-00002.d/x.gguf"),
        ("shard_mmproj", "mmproj-00001-of-00002.gguf"), ("shard_trailing_dot", "m-00001-of-00002.mmproj"),
    ]:
        add(name, [f(path, size=2)])
    # Not .gguf paths still go through the shard rule when they are support files; and
    # trailing-newline names (skipped, since "\n" breaks the suffix) must agree too.
    add("newline_suffix_skipped", [f("m-00001-of-00002.gguf\n", size=1), f("m.gguf\n")])
    add("kelvin_tokenizer", [f("toKenizer.model", size=1), f("TOKENIZER.MODEL")])
    add("dotted_capital_i_suffix", [f("chat_template.jİnja"), f("x.gguİ")])
    add("traversal_paths_listed_verbatim", [f("../../etc/x.gguf", size=1), f("/abs/y.gguf"), f("a\\b.gguf"),
                                            f("..\\..\\z-Q4_0.gguf"), f("./.gguf"), f(".gguf")])
    add("control_and_nul", '[{"type":"file","path":"a\\u0000b\\u001f-Q4_0.gguf","size":1}]')

    # Sizes: every JSON type through `int((lfs or {}).get("size") or size or 0)`.
    sizes = {
        "int": 42, "zero": 0, "negative": -5, "true": True, "false": False, "null": None,
        "float_trunc": 1.9, "float_neg_trunc": -1.9, "float_neg_half": -0.5, "float_big": 1e300,
        "float_2_53": 9007199254740993.0, "float_tiny": 5e-324, "float_neg_zero": -0.0,
        "str_digits": "123", "str_spaces": " \t12\n ", "str_underscores": "1_000_000",
        "str_double_underscore": "1__0", "str_leading_underscore": "_1", "str_trailing_underscore": "1_",
        "str_plus": "+5", "str_minus": "-5", "str_minus_zero": "-0", "str_leading_zeros": "007",
        "str_arabic": "١٢", "str_fullwidth": "１２", "str_nel_space": "\u0085 7",
        "str_ideographic_space": "　7　", "str_ascii_fs": "\u001c7", "str_empty": "",
        "str_blank": "  ", "str_zero": "0", "str_float": "1.5", "str_exp": "1e3", "str_hex": "0x10",
        "str_sign_space": "- 1", "str_double_sign": "--1", "str_mixed_digits": "1٢３",
        "str_superscript": "²", "str_nul": "1\u00002", "str_underscore_after_sign": "-_1",
        "str_long": "9" * 400, "list_empty": [], "list": [1], "dict_empty": {}, "dict": {"a": 1},
    }
    for name, value in sizes.items():
        add(f"size_{name}", [f("s.gguf", size=value)])
        add(f"lfs_size_{name}", [f("s.gguf", size=3, lfs={"size": value})])
    for name, literal in [("huge_int", "1" + "0" * 60), ("neg_huge_int", "-" + "9" * 80), ("exp_int", "1E2"),
                          ("frac_exp", "12.5e1"), ("overflow", "1e400"), ("underflow", "1e-400"),
                          ("nan", "NaN"), ("inf", "Infinity"), ("neg_inf", "-Infinity"), ("neg_zero_int", "-0")]:
        add(f"size_literal_{name}", f'[{{"type":"file","path":"s.gguf","size":{literal}}}]')
        add(f"lfs_literal_{name}", f'[{{"type":"file","path":"s.gguf","size":3,"lfs":{{"size":{literal}}}}}]')

    # lfs that is not an object.
    for name, value in {"str": "x", "list_empty": [], "list": [1], "zero": 0, "one": 1, "true": True,
                        "false": False, "null": None, "empty_str": ""}.items():
        add(f"lfs_{name}", [f("l.gguf", size=4, lfs=value)])

    # Entries that are not objects, and paths that are not strings.
    for name, value in {"int": 5, "str": "x.gguf", "null": None, "list": [], "bool": True}.items():
        add(f"entry_{name}", [f("ok.gguf"), value])
    for name, value in {"int": 5, "null": None, "list": ["a.gguf"], "dict": {}, "bool": False}.items():
        add(f"path_{name}", [{"type": "file", "path": value}])
    add("bad_size_on_skipped_entry", [f("README.md", size="nope"), f("ok.gguf", size=1)])
    add("bad_size_after_good", [f("ok.gguf", size=1), f("bad.gguf", size="nope")])

    # Seeded random names from an alphabet of every character class the rules care about.
    rng = random.Random(964)
    alphabet = list("-._/ QqIiFfBbPpKkMmSsXxLl0123456789") + [
        "İ", "ı", "ſ", "K", "٤", "٠", "４", "²", "é",
        "́", "\u0085", "　", "\n", "-of-", "-00001-of-00002", ".gguf", ".GGUF", "mmproj",
        "tokenizer.model", "Q4_K_M", "IQ2_XXS", "BF16", "F16", "fp8", "\U0001d7cf"]
    for i in range(400):
        name = "".join(rng.choice(alphabet) for _ in range(rng.randint(0, 12)))
        if rng.random() < 0.7:
            name += rng.choice([".gguf", "-00002-of-00003.gguf", ".GGUF", "mmproj.gguf", ""])
        size = rng.choice([0, 1, 2**40, "77", " 8 ", "٣", -3, 2.5, True, None])
        add(f"random_{i:03d}", [f(name, size=size)])
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--model-manager", required=True, type=Path,
                    help="noevia-services model-manager directory (holds app/model_files.py)")
    args = ap.parse_args()
    if sys.version_info[:2] != SERVICE_PYTHON:
        print(f"warning: the service runs Python {SERVICE_PYTHON}; this is {sys.version_info[:2]}",
              file=sys.stderr)
    sys.path.insert(0, str(args.model_manager.resolve()))
    from app.model_files import files_from_tree_py  # noqa: PLC0415

    (CRATE / "src" / "pytables.rs").write_text(tables())
    fixtures = []
    for name, text in cases():
        try:
            expect = {"files": files_from_tree_py(json.loads(text))}
        except Exception as e:  # noqa: BLE001 - any exception is the reference refusing the input
            expect = {"error": type(e).__name__}
        fixtures.append({"name": name, "input": text, "expect": expect})
    names = [c["name"] for c in fixtures]
    assert len(names) == len(set(names))
    doc = {"version": 1, "unidata_version": unicodedata.unidata_version,
           "reference": "noevia-services model-manager/app/model_files.py files_from_tree_py",
           "cases": fixtures}
    path = CRATE / "tests" / "fixtures" / "model-files.v1.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(doc, indent=1, ensure_ascii=True) + "\n")
    print(f"{len(fixtures)} cases -> {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
