//! Differential test against the Python reference: every case in
//! tests/fixtures/model-files.v1.json (generated by tools/gen-model-files.py from
//! noevia-services' model_files.py) must give exactly the Python result, or an error where
//! Python raised. The same file is committed in noevia-services, where the binary is checked
//! against the live Python function too.
//!
//! The fixture file is read with this crate's own JSON reader, which keeps integers exact
//! (serde_json would refuse or round the very large sizes some cases produce).
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use model_files::json::{self, Value};

fn fixtures() -> Value {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/model-files.v1.json"
    ))
    .expect("fixture file");
    json::parse(&text).expect("fixture JSON")
}

fn str_of(v: Option<&Value>) -> &str {
    match v {
        Some(Value::Str(s)) => s,
        other => panic!("expected a string, got {other:?}"),
    }
}

#[test]
fn tables_match_the_fixture_python() {
    assert_eq!(
        str_of(fixtures().get("unidata_version")),
        model_files::pytables::UNIDATA_VERSION
    );
}

#[test]
fn every_fixture_agrees_with_python() {
    let doc = fixtures();
    let Some(Value::Arr(cases)) = doc.get("cases") else {
        panic!("no cases");
    };
    assert!(cases.len() >= 500, "fixture table shrank: {}", cases.len());
    let mut agreed = 0;
    let mut errors = 0;
    for case in cases {
        let name = str_of(case.get("name"));
        let input = str_of(case.get("input"));
        let expect = case.get("expect").expect("expect");
        let got = model_files::files_from_tree_json(input.as_bytes());
        match (expect.get("files"), got) {
            (Some(want), Ok(out)) => {
                let ours = json::parse(&out).expect("our output is JSON");
                assert_eq!(ours.get("files"), Some(want), "{name}");
                agreed += 1;
            }
            (None, Err(_)) => {
                errors += 1;
                agreed += 1;
            }
            (Some(_), Err(e)) => panic!("{name}: Python accepted, Rust refused: {e}"),
            (None, Ok(out)) => panic!("{name}: Python raised, Rust returned {out}"),
        }
    }
    assert_eq!(agreed, cases.len());
    assert!(errors > 20, "expected the error cases to be exercised");
    println!(
        "model-files differential: {agreed}/{} agree ({errors} where both refuse)",
        cases.len()
    );
}
