//! Differential test against the Python reference: every case in
//! tests/fixtures/model-autoconfig.v1.json (generated by tools/gen-model-autoconfig.py from
//! noevia-services' autoconfig_core.py `size_plan`) must give exactly the Python plan (every
//! int an int, every float the same float) or, where Python raised, an error naming the same
//! exception type. The same file is committed in noevia-services, where the binary is also
//! checked against the live Python function on a seeded random corpus.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use model_files::json::{self, Value};

fn fixtures() -> Vec<Value> {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/model-autoconfig.v1.json"
    ))
    .expect("fixture file");
    match json::parse(&text).expect("fixture JSON").get("cases") {
        Some(Value::Arr(cases)) => cases.clone(),
        other => panic!("no cases: {other:?}"),
    }
}

/// Equality as Python's json round trip sees it: objects as maps, Int and Float distinct,
/// NaN equal to NaN, -0.0 distinct from 0.0.
fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Float(x), Value::Float(y)) => {
            x.to_bits() == y.to_bits() || (x.is_nan() && y.is_nan())
        }
        (Value::Arr(x), Value::Arr(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(p, q)| same(p, q))
        }
        (Value::Obj(x), Value::Obj(y)) => {
            x.len() == y.len() && x.iter().all(|(k, v)| b.get(k).is_some_and(|w| same(v, w)))
        }
        _ => a == b,
    }
}

#[test]
fn rust_agrees_with_python_on_every_fixture() {
    let cases = fixtures();
    assert!(cases.len() >= 150, "fixture too small: {}", cases.len());
    let mut raised = 0;
    for case in &cases {
        let name = match case.get("name") {
            Some(Value::Str(s)) => s.clone(),
            _ => panic!("unnamed case"),
        };
        let input = match case.get("input") {
            Some(Value::Str(s)) => s.clone(),
            _ => panic!("{name}: no input"),
        };
        let expect = case.get("expect").expect("expect");
        let got = model_autoconfig::size_plan_json(input.as_bytes());
        match (expect.get("error"), got) {
            (Some(Value::Str(kind)), Err(e)) => {
                raised += 1;
                assert_eq!(e.code(), format!("python:{kind}"), "{name}");
            }
            (None, Ok(text)) => {
                let plan = json::parse(&text).expect("plan JSON");
                assert!(same(&plan, expect), "{name}:\n rust {text}");
            }
            (want, got) => panic!("{name}: python {want:?}, rust {got:?}"),
        }
    }
    assert!(
        raised > 0,
        "the fixture must cover the reference's exceptions"
    );
}
