//! Differential test of `check` (autoconfig slices 3-6: speculative-decoding profiles, the
//! companion-file name rules, diff and presentation, baseline parsing) against the Python
//! reference: every case in tests/fixtures/model-autoconfig-present.v1.json (generated by
//! tools/gen-model-autoconfig.py from noevia-services' autoconfig_core.py `check_reference`)
//! must give exactly Python's answer or, where Python raised, an error naming the same exception
//! type. Cases named "[stricter] ..." are inputs the port refuses on purpose (see pystr.rs and
//! files.rs): there the answer must be a refusal that is not a Python exception.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic
)]

use model_autoconfig::Error;
use model_files::json::{self, Value};

fn cases() -> Vec<Value> {
    let text = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/model-autoconfig-present.v1.json"
    ))
    .expect("fixture file");
    match json::parse(&text).expect("fixture JSON").get("cases") {
        Some(Value::Arr(cases)) => cases.clone(),
        other => panic!("no cases: {other:?}"),
    }
}

/// Equality as Python's json round trip sees it (objects as maps, Int and Float distinct,
/// NaN equal to NaN).
fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Float(x), Value::Float(y)) => {
            x.to_bits() == y.to_bits() || (x.is_nan() && y.is_nan())
        }
        (Value::Arr(x), Value::Arr(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(p, q)| same(p, q))
        }
        (Value::Obj(x), Value::Obj(y)) => {
            x.len() == y.len() && x.iter().all(|(k, v)| b.get(k).is_some_and(|w| same(v, w)))
        }
        _ => a == b,
    }
}

#[test]
fn rust_agrees_with_python_on_every_present_fixture() {
    let cases = cases();
    assert!(cases.len() >= 1600, "fixture too small: {}", cases.len());
    let mut raised = 0;
    let mut stricter = 0;
    let mut agreed = std::collections::BTreeMap::<String, usize>::new();
    for case in &cases {
        let Some(Value::Str(name)) = case.get("name") else {
            panic!("unnamed case")
        };
        let Some(Value::Str(input)) = case.get("input") else {
            panic!("{name}: no input")
        };
        let expect = case.get("expect").expect("expect");
        let got = model_autoconfig::check_json(input.as_bytes());
        if name.starts_with("[stricter]") {
            match got {
                Err(Error::Python(kind)) => {
                    panic!("{name}: a Python exception {kind}, not a refusal")
                }
                Err(_) => stricter += 1,
                Ok(text) => panic!("{name}: answered {text}"),
            }
            continue;
        }
        match (expect.get("error"), got) {
            (Some(Value::Str(kind)), Err(e)) => {
                raised += 1;
                assert_eq!(e.code(), format!("python:{kind}"), "{name}");
            }
            (None, Ok(text)) => {
                let answer = json::parse(&text).expect("answer JSON");
                assert!(
                    same(&answer, expect),
                    "{name}:\n input  {input}\n rust   {text}\n python {expect:?}"
                );
                if let Value::Obj(parts) = &answer {
                    for (k, _) in parts {
                        *agreed.entry(k.clone()).or_default() += 1;
                    }
                }
            }
            (want, got) => panic!("{name}: python {want:?}, rust {got:?}\n input {input}"),
        }
    }
    for part in ["spec", "files", "present", "baseline"] {
        assert!(
            agreed.get(part).copied().unwrap_or(0) > 300,
            "coverage of {part}: {agreed:?}"
        );
    }
    assert!(
        raised > 10 && stricter >= 8,
        "raised {raised}, stricter {stricter}"
    );
}
